
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: test
    virtual-host: /
  jpa:
    hibernate:
      ddl-auto: update 
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션
#   datasource:
#     driver-class-name: org.postgresql.Driver
#     url: jdbc:postgresql://localhost:5435/api015-database
#     username: api015-database
#     password: api015-database

logging:
  level:
    root: debug
    org.hibernate.SQL: debug
    # org.hibernate.type: trace
    
server:
  port: 18082

com:
  soda_flavour:
    train:
      rabbit_mq:
        exchange: soda_flavour
        inbound: inbound_queue





###############################
# spring amqp
###############################
# spring.rabbitmq.host=localhost
# spring.rabbitmq.port=5672
# spring.rabbitmq.username=test
# spring.rabbitmq.password=test
# spring.rabbitmq.virtual-host=/

