spring:
  data:
    rest:
      detection-strategy: ANNOTATED
 
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션
#   datasource:
#     driver-class-name: org.postgresql.Driver
#     url: jdbc:postgresql://localhost:5435/api-database
#     username: api-database
#     password: api-database

# feign:
#   client:
#     config:
#       default:
#         connectTimeout: 3000
#         readTimeout: 3000

logging:
  level:
    root: debug
    org.hibernate.SQL: debug
    # org.hibernate.type: trace
    
server:
  port: 19909
